analytics: {}
color:
  brandColors:
    - '#C8E0D8'
    - '#001828'
    - '#888880'
    - '#4098B8'
    - '#70C8D8'
  brandStrength: 1
  lightness: 0.393444
  rhythmicContrast: 0.897852
  saturation: 0.329172
cta: {}
layout_spectrum: 0
name: Matt Metrovich
opengraph: {}
purpose: []
typography_spectrum: 0.568412
