analytics: {}
color:
  brandColors:
    - '#000000'
    - '#005F85'
    - '#000000'
    - '#00A0E0'
    - '#000000'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 1
  saturation: 0
cta: {}
layout_spectrum: 0.178209
name: Matt Metrovich
opengraph: {}
purpose: []
typography_spectrum: 0.42652
