name: Matt Metrovich
favicon: null
layout_spectrum: 0.28651410597376525
typography_spectrum: 0.3616531507577747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4840101369190961
  lightness: 0.3934441714081913
  saturation: 0.3291720603592694
  rhythmicContrast: 0.8978525947313756
purpose: []
